### ISSUE TITLE
Custom TypeSerializer not used for serialization

### ISSUE THREAD

**Issue by Flaflo** [SpongePowered/Configurate#123]
I registered a custom type serializer to a gson config loader
so now deserializing is working correct but serializing is not even called when saving.

```java
TypeSerializerCollection serializerCollection = TypeSerializers.newCollection();
serializerCollection.registerType(TypeToken.of(Color.class), new ColorSerializer());

this.configLoader = GsonConfigurationLoader.builder().setFile(file).setDefaultOptions(ConfigurationOptions.defaults().setSerializers(serializerCollection)).build();
```

```java
this.configLoader.save(this.config);
```

**Comment by zml2008** [comment]
Unfortunately this issue is quite old and doesn't have enough information to be able to reproduce the original issue. I'll be closing this issue for now but if you can provide a standalone, fully working example (or even better, a unit test) that reproduces this issue on the latest `master` I'll be happy to look into the issue again.
