### ISSUE TITLE
Unable to specify more specific TypeSerializer for custom class extending an already registered TypeSerializer of it's super class

### ISSUE THREAD

**Issue by nossr50** [SpongePowered/Configurate#132]
As the title says, @gabizou will know what I'm talking about as he asked me to submit this issue

**Comment by gabizou** [comment]
Basically put, if you want to register a custom TypeSerializer for your own `MyCustomEnum` that is still an `Enum`, Configurate will default to searching for the first type serializer, which would be the default one (that resorts to the `enum.name()` value), where the custom type serializer may want to emit a different value to the ConfigurationNode.

**Comment by dualspiral** [comment]
[This commit isn't the solution for that problem](https://github.com/SpongePowered/configurate/commit/9c2bdc73dd5a253794b7596f6d8cfd4dd06eb5bb) - though it goes _some_ way to working around it in this scenario. All that the commit does is make serialisers that are registered later take precidence when before it was the earlier ones that take precidence. It's nothing to do with sub/super classes. I could register `HashSet` then `Set`, and the `Set` serialiser would always be used. I'm also wary about that commit breaking previously expected (or otherwise incorrectly assumed) behaviour, as now this means that latest registered takes precidence, loading a config file with this version from a file created with a previous version _may_ now load different results - but then again, this should have been noticed before by developers using Configurate and I doubt this will be an issue as they will have worked around it anyway - the only issue will be if developers have already worked around this by making a new child and registered things in the first in wins that is currently released - this might break their configs.

Back on this issue itself - one option that can be used to work around it right now is to get a `newChild()` from the type serialisers, register your serialisers to that, and use that child collection with your configuration files. You can make children of children if necessary - though it will be messy. [The child is checked before the parent](https://github.com/SpongePowered/configurate/blob/9c2bdc73dd5a253794b7596f6d8cfd4dd06eb5bb/configurate-core/src/main/java/ninja/leaping/configurate/objectmapping/serialize/TypeSerializerCollection.java#L48) and would at least let you register your serialisers in the way you want them.

**Comment by nossr50** [comment]
I like the solution @kashike implemented, although it'd be nice if we could pass arguments when registering for priority or something along those lines.

**Comment by dualspiral** [comment]
Honestly, I don't like it and, as I said, this doesn't fix this issue at all. I'm sure it was intended as a quick workaround, but it really doesn't fix the problem and, as it stands, means that the expected defaults could be overwritten. Using `newChild` is meant to be a safer way to do this, as anything you register to the child takes priority, while not affecting other plugins or systems that use the basic defaults. Unfortunately, at least in Sponge, developers just tack on their requirements to the default collection - in which case the "first wins" scenario means that a plugin can't overwrite defaults and cause havoc. Plugins or other systems shouldn't be able to **globally** override the type serialiser collection and this commit causes that with no recourse.

I'm not dismissing this issue out of hand, it's valid and does need addressing. What I'm saying is that the commit doesn't actually fix it at all - it just changes the convention of the priority of new serialisers. For 3.x, at least, perhaps a way to do this is without breaking anything to allow adding new children with a selection strategy for their collections (such as FIRST_WINS or LAST_WINS or something potentially more complex that does subtype/supertype ordering) so that you can have this as an option for children you create.

I'm going to reopen this for now because this issue isn't fixed, as per my previous comment.

**Comment by nossr50** [comment]
That's a good point, thanks for the reply @dualspiral

**Comment by nossr50** [comment]
Thinking more on it, the global serializers really should be immutable.

As long as I can make and manipulate a new mutable collection of serializers with the default collection included, that would be good enough for me. Ideally being able to prioritize which serializer gets loaded when registering them or something to that effect.

**Comment by dualspiral** [comment]
Apologies, I meant to be respond to this earlier but life got in the way... then I forgot.

> Thinking more on it, the global serializers really should be immutable.

Yep, absolutely - something to think about for the next major version.

> As long as I can make and manipulate a new mutable collection of serializers with the default collection included

That's _effectively_ what `newChild()` does now, anything you put in your own collection will effectively overwrite the parent. You then just need to make sure your configuration loaders/object mappers use your collection rather than the straight up global one. The "first wins" strategy applies to things in the _same_ collection (i.e. not child/parent) so you should be okay, as long as you are mindful of the order in which things are registered. This means that in released versions of configurate that you register more specific types to your child first - the parent is only checked for a matching serialiser **if** nothing in the child matches the incoming type.

So, it should be possible to do what you want to do now - it just could be better.

As a quick "fix" to enable kashike's system on an opt-in basis, we could add a method `TypeSerializerCollection#newChild(AdditionStrategy)` to Configurate to control where new serialisers are added in the child (name is probably rubbish and could be changed) - at least offering `FIRST_WINS` (default, previous behaviour) and `LAST_WINS`. The structure of Configurate's type serialiser collections are somewhat weird and so it's not quite as simple as that - but it might be worth doing while we still have to support 3.x.

I'm pretty sure TSCs will be ripped apart for 4.x...

**Comment by nossr50** [comment]
So is anyone actually going to make the changes suggested by dual spiral? I need to update my code but I'm being lazy 😸 

@dualspiral 
@kashike

**Comment by dualspiral** [comment]
I had something that I never pushed up because I worked on it offline then forgot about it. PR with my suggestions are in #135.
