### ISSUE TITLE
Null return policy

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Configurate#139]
In API7 and before, configurate was in separate namespace, but in API8, configurate will be in same namespace as SpongeAPI.
SpongeAPI forbids returning nulls, but configurate can return nulls.

1. Wrap returns in Optional
2. Throw exception if null
3. Leave as is

More suggestions are welcome

**Comment by FerusGrim** [comment]
IMO, leave as-is.

There's a fundamental difference between Sponge's disdain for `null` and how a general configuration library should view `null`. A configuration value not existing is a valid state for a configuration file.

Configurate already supports providing a default value if you don't want to accept a `null` value as a valid return.

**Comment by zml2008** [comment]
So I've tried a few times to make Configurate work with `Optional`s, but due to Configurate's defaults system and its ability to write defaults back to the node on gets, switching to Optionals would result in a loss of functionality.

The realistic options going forward are:

- keep things as they are, perhaps doing a thorough review of nullability annotations to make sure we are providing accurate hints
- Switch to a class that has the same functionality as Optional but that is specific to Configurate and can handle writing back defaults. I don't think this is the right way to go.

There are upcoming API changes like `ValueReferences` (See #142) that may resolve some of the nullability concerns as well -- but 4.0 has a little while before it needs to be ready, so we can let some ideas grow for a bit.

**Comment by zml2008** [comment]
Alright, with the checkstyle coming in i'll be officially enforcing no optionals across Configurate. Nullability annotations will be verified and improved component-by-component. I'll be looking for static analysis tools to verify nullability automatically too.
