### ISSUE TITLE
Add a set serializer to the default type serializers

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Configurate#89]
I've seen this as a common desire, because Nucleus had its own for quite a while and now Sponge does as well. I'd assume others may have a use for one as well since it's such a common type.

I guess Craftbook had its own as well.

**Comment by zml2008** [comment]
Yeah I've been mildly against this since (apart from yaml) most configuration formats don't make much distinction between lists and sets, so any developer using sets would result in their users being unable to maintain whatever order they choose in lists within configurations (the same issue that people complain about with maps in hocon) -- and in most configuration usecases either sets or lists could be used. 

However, if people want/need sets then it's not that big of a deal to add a set serializer.

**Comment by ryantheleach** [comment]
How hard would it be to use some form of SortedSet for the sole purpose of maintaining config ordering? Still would be able to enforce uniqueness, 

The Sort could either be a natural sorting enforced by the plugin, or fallback to user order.

**Comment by zml2008** [comment]
Fixed in fcf3e34431af6460d3ad974e5cd8e5d31189d4db
